import { getAll, put, queueChange } from "./db.js";
import { nowISO, makeId } from "./utils.js";
import { awardXP } from "./game.js";
export async function ensureCajuStructure(){
 const [institutions,accounts]=await Promise.all([getAll("instituicoes"),getAll("contas")]); const caju=institutions.find(i=>norm(i.nome).includes("caju")||norm(i.nome_curto).includes("caju")); if(!caju)return{alimentacao:null,livre:null};
 const list=accounts.filter(a=>a.instituicao_id===caju.instituicao_id&&a.status!=="inativo"); let alimentacao=list.find(a=>a.tipo==="beneficio"||norm(a.nome).includes("alimentacao")); let livre=list.find(a=>a.tipo==="saldo_livre"||norm(a.nome).includes("livre")); const now=nowISO();
 if(!alimentacao){const legacy=list.find(a=>a.conta_id!==livre?.conta_id); alimentacao=legacy?{...legacy,nome:"Caju Alimentação",tipo:"beneficio",atualizado_em:now}:{conta_id:"conta_caju_alimentacao",instituicao_id:caju.instituicao_id,nome:"Caju Alimentação",tipo:"beneficio",saldo_inicial:0,saldo_atual:0,status:"ativo",criado_em:now,atualizado_em:now}; await put("contas",alimentacao);await queueChange("CONTAS",alimentacao)}
 if(!livre){livre={conta_id:"conta_caju_livre",instituicao_id:caju.instituicao_id,nome:"Caju Saldo Livre",tipo:"saldo_livre",saldo_inicial:0,saldo_atual:0,status:"ativo",criado_em:now,atualizado_em:now};await put("contas",livre);await queueChange("CONTAS",livre)} return{alimentacao,livre};
}
export async function getCajuMonthlySuggestion(){const{alimentacao}=await ensureCajuStructure();if(!alimentacao)return null;const now=new Date(),due=firstWeekday(now.getFullYear(),now.getMonth());if(dayStamp(now)<dayStamp(due))return null;const tx=await getAll("transacoes"),ym=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`;if(tx.some(t=>t.tipo==="entrada"&&t.conta_id===alimentacao.conta_id&&String(t.data||"").startsWith(ym)&&String(t.observacao||"").includes("orion:caju_mensal")))return null;return{value:400,date:iso(due),account:alimentacao}}
export async function registerCajuMonthlyCredit(){const sug=await getCajuMonthlySuggestion();if(!sug)throw new Error("Crédito da Caju já registrado ou ainda não previsto.");const cats=await getAll("categorias");const cat=cats.find(c=>norm(c.nome)==="trabalho")||cats.find(c=>String(c.tipo_permitido||"")==="entrada")||cats.find(c=>String(c.tipo_permitido||"")==="entrada_saida");if(!cat)throw new Error("Nenhuma categoria de entrada disponível.");const now=nowISO(),r={transacao_id:makeId("trx"),data:sug.date,descricao:"Caju mensal",valor:400,tipo:"entrada",categoria_id:cat.categoria_id,subcategoria_id:"",conta_id:sug.account.conta_id,forma_pagamento:"beneficio",cartao_id:"",observacao:"Crédito recorrente confirmado · orion:caju_mensal",criado_em:now,atualizado_em:now};await put("transacoes",r);await queueChange("TRANSACOES",r);await awardXP("rotina",`caju:${r.data.slice(0,7)}`,10,"Crédito mensal da Caju registrado.");return r}
function firstWeekday(y,m){const d=new Date(y,m,1,12);while(d.getDay()===0||d.getDay()===6)d.setDate(d.getDate()+1);return d}function dayStamp(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime()}function iso(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}function norm(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
